/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* NCCL_TESTS_SDT_BENCH_TEST_START ( int iterations ) */
#if defined STAP_SDT_V1
#define NCCL_TESTS_SDT_BENCH_TEST_START_ENABLED() __builtin_expect (bench_test_start_semaphore, 0)
#define nccl_tests_sdt_bench_test_start_semaphore bench_test_start_semaphore
#else
#define NCCL_TESTS_SDT_BENCH_TEST_START_ENABLED() __builtin_expect (nccl_tests_sdt_bench_test_start_semaphore, 0)
#endif
__extension__ extern unsigned short nccl_tests_sdt_bench_test_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define NCCL_TESTS_SDT_BENCH_TEST_START(arg1) \
DTRACE_PROBE1 (nccl_tests_sdt, bench_test_start, arg1)

/* NCCL_TESTS_SDT_BENCH_TEST_STOP ( int iterations ) */
#if defined STAP_SDT_V1
#define NCCL_TESTS_SDT_BENCH_TEST_STOP_ENABLED() __builtin_expect (bench_test_stop_semaphore, 0)
#define nccl_tests_sdt_bench_test_stop_semaphore bench_test_stop_semaphore
#else
#define NCCL_TESTS_SDT_BENCH_TEST_STOP_ENABLED() __builtin_expect (nccl_tests_sdt_bench_test_stop_semaphore, 0)
#endif
__extension__ extern unsigned short nccl_tests_sdt_bench_test_stop_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define NCCL_TESTS_SDT_BENCH_TEST_STOP(arg1) \
DTRACE_PROBE1 (nccl_tests_sdt, bench_test_stop, arg1)

/* NCCL_TESTS_SDT_START_COLL_START ( int iter ) */
#if defined STAP_SDT_V1
#define NCCL_TESTS_SDT_START_COLL_START_ENABLED() __builtin_expect (start_coll_start_semaphore, 0)
#define nccl_tests_sdt_start_coll_start_semaphore start_coll_start_semaphore
#else
#define NCCL_TESTS_SDT_START_COLL_START_ENABLED() __builtin_expect (nccl_tests_sdt_start_coll_start_semaphore, 0)
#endif
__extension__ extern unsigned short nccl_tests_sdt_start_coll_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define NCCL_TESTS_SDT_START_COLL_START(arg1) \
DTRACE_PROBE1 (nccl_tests_sdt, start_coll_start, arg1)

/* NCCL_TESTS_SDT_START_COLL_STOP ( int iter ) */
#if defined STAP_SDT_V1
#define NCCL_TESTS_SDT_START_COLL_STOP_ENABLED() __builtin_expect (start_coll_stop_semaphore, 0)
#define nccl_tests_sdt_start_coll_stop_semaphore start_coll_stop_semaphore
#else
#define NCCL_TESTS_SDT_START_COLL_STOP_ENABLED() __builtin_expect (nccl_tests_sdt_start_coll_stop_semaphore, 0)
#endif
__extension__ extern unsigned short nccl_tests_sdt_start_coll_stop_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define NCCL_TESTS_SDT_START_COLL_STOP(arg1) \
DTRACE_PROBE1 (nccl_tests_sdt, start_coll_stop, arg1)

/* NCCL_TESTS_SDT_BARRIER_START ( int iterations ) */
#if defined STAP_SDT_V1
#define NCCL_TESTS_SDT_BARRIER_START_ENABLED() __builtin_expect (barrier_start_semaphore, 0)
#define nccl_tests_sdt_barrier_start_semaphore barrier_start_semaphore
#else
#define NCCL_TESTS_SDT_BARRIER_START_ENABLED() __builtin_expect (nccl_tests_sdt_barrier_start_semaphore, 0)
#endif
__extension__ extern unsigned short nccl_tests_sdt_barrier_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define NCCL_TESTS_SDT_BARRIER_START(arg1) \
DTRACE_PROBE1 (nccl_tests_sdt, barrier_start, arg1)

/* NCCL_TESTS_SDT_BARRIER_STOP ( int iterations ) */
#if defined STAP_SDT_V1
#define NCCL_TESTS_SDT_BARRIER_STOP_ENABLED() __builtin_expect (barrier_stop_semaphore, 0)
#define nccl_tests_sdt_barrier_stop_semaphore barrier_stop_semaphore
#else
#define NCCL_TESTS_SDT_BARRIER_STOP_ENABLED() __builtin_expect (nccl_tests_sdt_barrier_stop_semaphore, 0)
#endif
__extension__ extern unsigned short nccl_tests_sdt_barrier_stop_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define NCCL_TESTS_SDT_BARRIER_STOP(arg1) \
DTRACE_PROBE1 (nccl_tests_sdt, barrier_stop, arg1)

/* NCCL_TESTS_SDT_STREAM_SYNC_CUDA_STEAM_QUERY_START ( int gpu ) */
#if defined STAP_SDT_V1
#define NCCL_TESTS_SDT_STREAM_SYNC_CUDA_STEAM_QUERY_START_ENABLED() __builtin_expect (stream_sync_cuda_steam_query_start_semaphore, 0)
#define nccl_tests_sdt_stream_sync_cuda_steam_query_start_semaphore stream_sync_cuda_steam_query_start_semaphore
#else
#define NCCL_TESTS_SDT_STREAM_SYNC_CUDA_STEAM_QUERY_START_ENABLED() __builtin_expect (nccl_tests_sdt_stream_sync_cuda_steam_query_start_semaphore, 0)
#endif
__extension__ extern unsigned short nccl_tests_sdt_stream_sync_cuda_steam_query_start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define NCCL_TESTS_SDT_STREAM_SYNC_CUDA_STEAM_QUERY_START(arg1) \
DTRACE_PROBE1 (nccl_tests_sdt, stream_sync_cuda_steam_query_start, arg1)

/* NCCL_TESTS_SDT_STREAM_SYNC_CUDA_STEAM_QUERY_STOP ( int gpu ) */
#if defined STAP_SDT_V1
#define NCCL_TESTS_SDT_STREAM_SYNC_CUDA_STEAM_QUERY_STOP_ENABLED() __builtin_expect (stream_sync_cuda_steam_query_stop_semaphore, 0)
#define nccl_tests_sdt_stream_sync_cuda_steam_query_stop_semaphore stream_sync_cuda_steam_query_stop_semaphore
#else
#define NCCL_TESTS_SDT_STREAM_SYNC_CUDA_STEAM_QUERY_STOP_ENABLED() __builtin_expect (nccl_tests_sdt_stream_sync_cuda_steam_query_stop_semaphore, 0)
#endif
__extension__ extern unsigned short nccl_tests_sdt_stream_sync_cuda_steam_query_stop_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define NCCL_TESTS_SDT_STREAM_SYNC_CUDA_STEAM_QUERY_STOP(arg1) \
DTRACE_PROBE1 (nccl_tests_sdt, stream_sync_cuda_steam_query_stop, arg1)

